### ISSUE TITLE
Improve tables for mobile devices

### ISSUE THREAD

**Issue by frdmn** [frdmn/blog.frd.mn#18]
<img width="418" alt="bildschirmfoto 2016-04-03 um 23 27 54" src="https://cloud.githubusercontent.com/assets/944459/14235065/db0a570c-f9f3-11e5-9858-ab056351a303.png">

**Comment by rnarian** [comment]
![untitled2](https://cloud.githubusercontent.com/assets/1174951/14253894/b74d9bcc-fa8d-11e5-97a3-7bc28bdaee0c.gif)
