### ISSUE TITLE
Disqus Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by rnarian** [frdmn/blog.frd.mn#33]
```
XMLHttpRequest cannot load https://disqus.com/api/3.0/forums/listThreads.json?... 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by rnarian** [comment]
→ Disqus application settings.

**Comment by ilanssari** [comment]
Hello @rnarian  im having the same problem now , did you found a solution ?

**Comment by frdmn** [comment]
Hi @ntdetect, I'm pretty sure that you just have to "whitelist" your domain (the one where you've embedded the Disqus snippet) in the Disqus _application settings_.

**Comment by ilanssari** [comment]
Hi @frdmn  thank you for your comment , i have added it in the trusted domains but nothings :\

**Comment by frdmn** [comment]
Can you screenshot/post the complete error message you're getting now?

**Comment by ilanssari** [comment]
this is the error :
![image](https://user-images.githubusercontent.com/15862306/31006283-ffe67c5c-a4f3-11e7-939b-0e48b141b972.png)
and this is the trusted domains :
![image](https://user-images.githubusercontent.com/15862306/31006326-2cf5e3fe-a4f4-11e7-961b-b6d315d9aab0.png)
thank youu

**Comment by ilanssari** [comment]
Hello i finally find the problem , it was an old api code who calls the "blog-ippon-fr" shortcode instead of "blogipponfr"

**Comment by IndraVikas** [comment]
Even after adding the domain as trusted domains. I am getting this error.
