### ISSUE TITLE
Remove copy-to-clipboard buttons in print view

### ISSUE THREAD

**Issue by frdmn** [frdmn/blog.frd.mn#52]
![](http://up.frd.mn/T4ny6KGlAa.png)

**Comment by rnarian** [comment]
:trollface:

**Comment by frdmn** [comment]
<img width="17" alt="bildschirmfoto 2016-04-12 um 21 52 44" src="https://cloud.githubusercontent.com/assets/944459/14473539/e9b74cfe-00f8-11e6-90d2-d62e56cfed38.png">
